name: Code Quality

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          working-dir: ./web

      - name: Run Biome
        working-directory: ./web
        run: biome ci
